---
# Based heavily on the Ansible documentation on EC2:
# http://docs.ansible.com/ec2_module.html
 - name: Provision an EC2 node
   hosts: local
   connection: local
   gather_facts: False
   tags: provisioning
   vars:
     instance_type: t2.micro
     security_group: sg_thingy
     image: ami-c8580bdf
     region: us-east-1
     keypair: newTest
   tasks:
     - name: Launch new Instance
       local_action: ec2 instance_tags="Name=AnsibleTest" group={{ security_group }} instance_type={{ instance_type}} image={{ image }} wait=true region={{ region }} keypair={{ keypair }}
       register: ec2
     - name: Add instance to local host group
       add_host: hostname={{ item.public_ip }} groupname=launched ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem
       with_items: "{{ ec2.instances }}"
     - name: Wait for SSH to come up
       local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
       with_items: "{{ ec2.instances }}"


 - name: With the newly provisioned EC2 node configure that thing
   hosts: launched 
   become: yes 
   remote_user: ubuntu 
   gather_facts: True
   environment:
     DOCKERBOT_TOKEN: xoxb-94302876704-pQsTlozMwGgXXK6iJaUGip12
   tasks:
     - name: Setting up Slack Token
       shell: export DOCKERBOT_TOKEN="xoxb-94302876704-pQsTlozMwGgXXK6iJaUGip12"
     - name: Adding another token to .bashrc
       shell: dest=~/.bashrc line='export DOCKERBOT_TOKEN="xoxb-94302876704-pQsTlozMwGgXXK6iJaUGip12"' insertafter='EOF' state=present
     - name: Setting up Docker for Deployment
       script: docker-deployment.sh
     - name: Deploying bot
       script: deploy-bot.sh
